const copy={
en:{atlasLink:"Atlas ↗",pilot:"Fethiye–Muğla field pilot",pilotNote:"Global model · locally calibrating",title:"What could grow here?",intro:"Add a few facts about your space. Ground compares useful crops, water demand and three seasonal scenarios before you plant.",locationLabel:"Where is the land?",locationHelp:"City or nearest town is enough. No title deed needed.",spaceLabel:"What kind of space?",terrace:"Terrace",garden:"Garden",field:"Field",orchard:"Orchard",areaLabel:"Growing area",sunLabel:"Direct sun",sunFull:"6+ hours",sunPart:"3–6 hours",sunLow:"Under 3 hours",waterLabel:"Water access",waterLow:"Limited",waterMedium:"Moderate",waterHigh:"Reliable",goalLabel:"Main priority",goalResilience:"Climate resilience",goalWater:"Use less water",goalFood:"Grow more food",goalIncome:"Income potential",goalCare:"Low maintenance",analyse:"Run first estimate",formNote:"No account. No land records. This first estimate stays on your device.",empty:"Your first land reading will appear here.",reading:"LAND READING",resultTitle:"Three ways to use this ground.",confidence:"MODEL CONFIDENCE",summaryArea:"AREA",summaryClimate:"CLIMATE",summaryWater:"WATER LIMIT",scenarioTitle:"SEASON RANGE",scenarioNote:"Not one forecast. Three plausible conditions.",hotDry:"HOT + DRY",normal:"TYPICAL",wet:"WETTER",yieldShift:"yield shift",historicRange:"historic range",improveLabel:"MAKE THIS READING BETTER",improveTitle:"Add evidence, not paperwork.",improveSoil:"Soil texture or a simple soil test",improveWater:"Actual irrigation capacity",improveHistory:"Last season’s crop and yield",save:"Save this reading",saved:"Saved on this device",edit:"Edit inputs",disclaimer:"Experimental decision support—not a guarantee of yield or a replacement for local soil testing and agronomic advice.",footer:"The global model starts broad. Real local seasons make it useful.",early:"EARLY LOCAL MODEL",global:"GLOBAL ESTIMATE",waterUnit:"L / SEASON",yieldUnit:"EST. YIELD",resilience:"HOT-DRY",high:"HIGH",medium:"MEDIUM",low:"LOW",reasonTerrace:"A compact mix that uses containers efficiently and keeps harvesting practical.",reasonWater:"Ranks well when water is the binding constraint.",reasonIncome:"Higher productive potential, with more exposure to price and management risk.",reasonResilience:"Balances useful yield with a smaller penalty in a hot, dry season.",reasonCare:"A perennial-leaning plan with fewer seasonal operations.",reasonFood:"Prioritises edible volume and a longer harvest window.",baseline:"BASELINE",tags:{lowWater:"lower water",resilient:"heat resilient",food:"food volume",income:"income option",perennial:"perennial",quick:"quick harvest"}},
tr:{atlasLink:"Atlas ↗",pilot:"Fethiye–Muğla saha pilotu",pilotNote:"Global model · yerel kalibrasyon",title:"Burada ne yetişebilir?",intro:"Alanınızla ilgili birkaç bilgi ekleyin. Ground, dikimden önce uygun ürünleri, su ihtiyacını ve üç mevsim senaryosunu karşılaştırır.",locationLabel:"Arazi nerede?",locationHelp:"Şehir veya en yakın ilçe yeterli. Tapu bilgisi gerekmiyor.",spaceLabel:"Nasıl bir alan?",terrace:"Teras",garden:"Bahçe",field:"Tarla",orchard:"Meyvelik",areaLabel:"Üretim alanı",sunLabel:"Doğrudan güneş",sunFull:"6+ saat",sunPart:"3–6 saat",sunLow:"3 saatten az",waterLabel:"Su imkânı",waterLow:"Kısıtlı",waterMedium:"Orta",waterHigh:"Güvenilir",goalLabel:"Öncelik",goalResilience:"İklim dayanıklılığı",goalWater:"Daha az su",goalFood:"Daha çok gıda",goalIncome:"Gelir potansiyeli",goalCare:"Az bakım",analyse:"İlk tahmini hesapla",formNote:"Hesap yok. Tapu kaydı yok. Bu ilk tahmin yalnızca cihazınızda kalır.",empty:"İlk arazi okumanız burada görünecek.",reading:"ARAZİ OKUMASI",resultTitle:"Bu alanı kullanmanın üç yolu.",confidence:"MODEL GÜVENİ",summaryArea:"ALAN",summaryClimate:"İKLİM",summaryWater:"SU SINIRI",scenarioTitle:"MEVSİM ARALIĞI",scenarioNote:"Tek tahmin değil, üç olası koşul.",hotDry:"SICAK + KURAK",normal:"TİPİK",wet:"DAHA YAĞIŞLI",yieldShift:"verim değişimi",historicRange:"tarihsel aralık",improveLabel:"BU HESABI İYİLEŞTİR",improveTitle:"Evrak değil, ölçüm ekleyin.",improveSoil:"Toprak yapısı veya basit toprak testi",improveWater:"Gerçek sulama kapasitesi",improveHistory:"Geçen sezonun ürünü ve verimi",save:"Bu okumayı kaydet",saved:"Bu cihaza kaydedildi",edit:"Bilgileri düzenle",disclaimer:"Deneysel karar desteğidir; verim garantisi veya yerel toprak testi ve ziraat danışmanlığının yerine geçmez.",footer:"Global model geniş başlar. Gerçek yerel sezonlar onu faydalı kılar.",early:"ERKEN YEREL MODEL",global:"GLOBAL TAHMİN",waterUnit:"L / SEZON",yieldUnit:"TAHMİNİ VERİM",resilience:"SICAK-KURAK",high:"YÜKSEK",medium:"ORTA",low:"DÜŞÜK",reasonTerrace:"Saksıları verimli kullanan, hasadı pratik tutan kompakt bir karışım.",reasonWater:"Su ana kısıt olduğunda güçlü bir seçenek.",reasonIncome:"Daha yüksek üretim potansiyeli; fiyat ve bakım riskine daha açık.",reasonResilience:"Faydalı verimi sıcak ve kurak mevsim dayanımıyla dengeler.",reasonCare:"Daha az sezonluk işlem isteyen, çok yıllık ağırlıklı bir plan.",reasonFood:"Yenilebilir miktarı ve uzun hasat dönemini önceliklendirir.",baseline:"BAZ",tags:{lowWater:"daha az su",resilient:"sıcağa dayanıklı",food:"gıda miktarı",income:"gelir seçeneği",perennial:"çok yıllık",quick:"hızlı hasat"}}
};

Object.assign(copy.en,{confidence:"DATA STAGE",pilotValue:"PILOT",early:"UNVALIDATED LOCAL ESTIMATE",global:"GLOBAL BASELINE",disclaimer:"Experimental, unvalidated ranges—not a guarantee of yield or a replacement for local soil testing and agronomic advice."});
Object.assign(copy.tr,{confidence:"VERİ AŞAMASI",pilotValue:"PİLOT",early:"DOĞRULANMAMIŞ YEREL TAHMİN",global:"GLOBAL BAŞLANGIÇ",disclaimer:"Deneysel ve henüz doğrulanmamış aralıklardır; verim garantisi veya yerel toprak testi ve ziraat danışmanlığının yerine geçmez."});

const crops=[
{id:"herbs",en:"Herbs + leafy greens",tr:"Otlar + yapraklılar",types:["terrace","garden"],water:260,yield:5.8,resilience:.72,care:.72,income:.45,tags:["quick","food"]},
{id:"tomato",en:"Cherry tomato + basil",tr:"Çeri domates + fesleğen",types:["terrace","garden","field"],water:520,yield:8.4,resilience:.48,care:.42,income:.76,tags:["food","income"]},
{id:"pepper",en:"Pepper + winter legume",tr:"Biber + kışlık baklagil",types:["garden","field"],water:440,yield:6.2,resilience:.57,care:.5,income:.8,tags:["food","income"]},
{id:"fig",en:"Fig + aromatic understory",tr:"İncir + aromatik alt örtü",types:["garden","field","orchard"],water:190,yield:2.7,resilience:.87,care:.82,income:.68,tags:["resilient","perennial"]},
{id:"pomegranate",en:"Pomegranate + winter legume",tr:"Nar + kışlık baklagil",types:["field","orchard","garden"],water:280,yield:3.8,resilience:.8,care:.66,income:.83,tags:["resilient","income"]},
{id:"olive",en:"Olive + managed groundcover",tr:"Zeytin + kontrollü yer örtüsü",types:["field","orchard"],water:125,yield:1.7,resilience:.9,care:.8,income:.7,tags:["lowWater","perennial"]},
{id:"thyme",en:"Thyme + sage strip",tr:"Kekik + adaçayı şeridi",types:["terrace","garden","field"],water:95,yield:1.05,resilience:.94,care:.9,income:.72,tags:["lowWater","resilient"]},
{id:"legume",en:"Chickpea + winter cover",tr:"Nohut + kışlık örtü",types:["field","garden"],water:145,yield:.28,resilience:.84,care:.74,income:.55,tags:["lowWater","resilient"]},
{id:"citrus",en:"Citrus + shaded herbs",tr:"Narenciye + gölge otları",types:["garden","orchard"],water:610,yield:4.5,resilience:.38,care:.54,income:.75,tags:["food","perennial"]},
{id:"courgette",en:"Courgette + chard",tr:"Kabak + pazı",types:["terrace","garden","field"],water:470,yield:7.1,resilience:.46,care:.48,income:.52,tags:["quick","food"]}
];

let lang=localStorage.getItem("ground-lang")||(navigator.language.toLowerCase().startsWith("tr")?"tr":"en");
let lastResult=null;
const form=document.getElementById("ground-form"),results=document.getElementById("results"),empty=document.getElementById("result-empty");

function setLanguage(next){lang=next;localStorage.setItem("ground-lang",lang);document.documentElement.lang=lang;document.querySelectorAll("[data-lang]").forEach(btn=>btn.classList.toggle("is-active",btn.dataset.lang===lang));document.querySelectorAll("[data-copy]").forEach(el=>{const value=copy[lang][el.dataset.copy];if(value)el.textContent=value});if(lastResult){lastResult.climate=climateFor(lastResult.location);renderResult(lastResult)}}
function climateFor(location){const value=location.toLocaleLowerCase("tr-TR");const local=/fethiye|muğla|mugla|dalaman|sey?dikemer/.test(value);const mediterranean=local||/antalya|izmir|bodrum|mersin|adana|athens|atina|barcelona|valencia|rome|roma|sicily|sicilia|lisbon|lizbon|marseille/.test(value);const temperate=/london|berlin|amsterdam|paris|copenhagen|stockholm|seattle|montreal/.test(value);return{local,name:mediterranean?(lang==="tr"?"AKDENİZ":"MEDITERRANEAN"):temperate?(lang==="tr"?"ILIMAN":"TEMPERATE"):(lang==="tr"?"GLOBAL TAHMİN":"GLOBAL ESTIMATE"),heat:mediterranean?1.15:temperate?.82:1}}
function calculate(data){const climate=climateFor(data.location),area=Math.max(1,Math.min(1000000,Number(data.area)||1)),waterFactor={low:.72,medium:1,high:1.13}[data.water],sunFactor={full:1,part:.76,low:.48}[data.sun],containerFactor=data.space==="terrace"?.74:data.space==="garden"?.9:1;const goalWeights={resilience:c=>c.resilience*1.35+c.care*.2,water:c=>(1-Math.min(c.water/700,1))*1.5+c.resilience*.5,food:c=>Math.min(c.yield/8,1)*1.4+c.resilience*.25,income:c=>c.income*1.35+c.resilience*.25,care:c=>c.care*1.45+c.resilience*.35};const ranked=crops.filter(c=>c.types.includes(data.space)).map(c=>({...c,score:goalWeights[data.goal](c)+(data.water==="low"?1-c.water/700:0)+(data.sun==="low"&&c.id==="herbs"?.35:0)})).sort((a,b)=>b.score-a.score).slice(0,3).map(c=>{const scaleArea=data.space==="terrace"?Math.min(area,120):area,yieldKg=c.yield*scaleArea*sunFactor*containerFactor*Math.min(waterFactor,1.04),waterL=c.water*scaleArea*climate.heat*(data.space==="terrace"?1.16:1)*(data.water==="low"?.78:1);return{...c,yieldLow:yieldKg*.76,yieldHigh:yieldKg*1.18,waterLow:waterL*.84,waterHigh:waterL*1.17}});return{...data,area,climate,ranked,confidence:climate.local?58:34}}
function formatNumber(number){return new Intl.NumberFormat(lang==="tr"?"tr-TR":"en-US",{maximumFractionDigits:number<100?1:0}).format(number)}
function reasonFor(data){if(data.space==="terrace")return copy[lang].reasonTerrace;return copy[lang]["reason"+data.goal.charAt(0).toUpperCase()+data.goal.slice(1)]}
function renderResult(data){const c=copy[lang];document.getElementById("result-location").textContent=data.location.toLocaleUpperCase(lang==="tr"?"tr-TR":"en-US");document.getElementById("confidence-value").textContent=`${data.confidence}%`;document.getElementById("confidence-label").textContent=data.climate.local?c.early:c.global;document.getElementById("summary-area").textContent=`${formatNumber(data.area)} m²`;document.getElementById("summary-climate").textContent=data.climate.name;document.getElementById("summary-water").textContent=c[data.water];document.getElementById("hot-yield").textContent=data.goal==="resilience"||data.goal==="water"?"−16%":"−29%";document.getElementById("wet-yield").textContent=data.water==="high"?"+6%":"+12%";document.getElementById("plan-list").innerHTML=data.ranked.map((plan,index)=>`<article class="plan-card"><span class="plan-rank">0${index+1}</span><div><h3 class="plan-name">${plan[lang]}</h3><p class="plan-reason">${reasonFor(data)}</p><div class="plan-tags">${plan.tags.map(tag=>`<span>${c.tags[tag]}</span>`).join("")}</div></div><div class="plan-metrics"><div><span>${c.waterUnit}</span><strong>${formatNumber(plan.waterLow)}–${formatNumber(plan.waterHigh)}</strong></div><div><span>${c.yieldUnit}</span><strong>${formatNumber(plan.yieldLow)}–${formatNumber(plan.yieldHigh)} kg</strong></div><div><span>${c.resilience}</span><strong>${plan.resilience>.82?c.high:plan.resilience>.55?c.medium:c.low}</strong></div><div><span>${c.baseline}</span><strong>${Math.round(plan.score*100)}</strong></div></div></article>`).join("");empty.hidden=true;results.hidden=false}

form.addEventListener("submit",event=>{event.preventDefault();lastResult=calculate(Object.fromEntries(new FormData(form).entries()));renderResult(lastResult);if(window.innerWidth<981)results.scrollIntoView({behavior:"smooth",block:"start"})});
document.querySelectorAll("[data-lang]").forEach(button=>button.addEventListener("click",()=>setLanguage(button.dataset.lang)));
document.getElementById("reset-plan").addEventListener("click",()=>document.getElementById("location").focus());
document.getElementById("save-plan").addEventListener("click",event=>{if(!lastResult)return;localStorage.setItem("ground-reading",JSON.stringify(lastResult));event.currentTarget.textContent=copy[lang].saved;event.currentTarget.classList.add("is-saved")});
function syncDataStage(){if(!lastResult)return;document.getElementById("confidence-value").textContent=copy[lang].pilotValue;document.getElementById("confidence-label").textContent=lastResult.climate.local?copy[lang].early:copy[lang].global}
form.addEventListener("submit",syncDataStage);
document.querySelectorAll("[data-lang]").forEach(button=>button.addEventListener("click",syncDataStage));
setLanguage(lang);
