(function(){
  "use strict";
  const c=(id,en,tr,zones,types,water,yieldValue,resilience,care,income,kind,plant,row,root,mixEn,mixTr,tags)=>({id,en,tr,climates:zones,types,water,yield:yieldValue,resilience,care,income,kind,plant,row,root,mixEn,mixTr,tags,regional:true});
  const M=["mediterranean"],A=["arid"],T=["temperate"],C=["cold"],S=["subtropical"],R=["tropical"];
  const garden=["garden","field"],orchard=["garden","field","orchard"],small=["terrace","garden","field"],field=["field"],warm=["garden","field","orchard"];
  window.GROUND_REGIONAL_CROPS=[
    c("caper","Caper + open mineral mulch","Kapari + açık mineral malç",[...M,...A],small,55,.45,.98,.92,.75,"perennial",150,220,45,"Keep the crown dry and the planting open; avoid a dense combustible hedge.","Kök boğazını kuru ve dikimi açık tutun; yoğun, yanıcı bir çit oluşturmayın.",["lowWater","resilient"]),
    c("fennel","Florence fennel + winter greens","Rezene + kışlık yapraklılar",M,garden,220,2.2,.76,.68,.61,"annual",30,55,35,"Use in cool-season blocks; keep wild fennel away where seed spread matters.","Serin dönem bloklarında kullanın; tohum yayılımının sorun olduğu yerde yabani rezeneyi ayırın.",["food","quick"]),
    c("bay","Bay laurel + shade herbs","Defne + gölge otları",M,orchard,120,.7,.91,.86,.65,"tree",400,450,65,"Allow for the mature crown; keep a clear trunk ring and managed understory.","Olgun taç için yer bırakın; gövde halkasını açık, alt katmanı kontrollü tutun.",["lowWater","perennial"]),
    c("sesame","Sesame + winter legume rotation","Susam + kışlık baklagil rotasyonu",[...M,...A],garden,150,.22,.9,.7,.73,"annual",15,55,30,"Use a warm, well-drained block and rotate with a cool-season legume.","Sıcak, iyi drene olan blokta kullanın; serin dönem baklagiliyle rotasyon yapın.",["lowWater","income"]),
    c("lentil","Lentil + cereal rotation","Mercimek + tahıl rotasyonu",[...M,...A,...T],field,95,.2,.91,.78,.59,"annual",5,25,25,"Keep sowing bands accessible and avoid repeating legumes in successive seasons.","Ekim şeritlerini erişilebilir tutun; baklagili art arda sezonlarda tekrarlamayın.",["lowWater","resilient"]),
    c("pistachio","Pistachio + sparse winter cover","Antep fıstığı + seyrek kış örtüsü",[...M,...A],orchard,105,.65,.93,.83,.9,"tree",650,700,90,"Confirm winter chill, polliniser ratio and cultivar before planting a permanent block.","Kalıcı blok kurmadan önce soğuklama, tozlayıcı oranı ve çeşidi doğrulayın.",["lowWater","income"]),

    c("datePalm","Date palm + seasonal alley","Hurma palmiyesi + mevsimlik koridor",A,orchard,420,2.6,.92,.64,.88,"tree",700,800,100,"Use only where winter cold is low; keep irrigation and harvest access independent.","Yalnızca kış soğuğunun düşük olduğu yerde kullanın; sulama ve hasat erişimini ayırın.",["resilient","income"]),
    c("jujube","Jujube + dry flowering strip","Hünnap + kurak çiçek şeridi",[...A,...M,...T],orchard,115,2,.94,.84,.7,"tree",450,500,70,"Keep the root zone open and monitor suckers before adding an understory.","Alt katman eklemeden önce kök alanını açık tutun ve dip sürgünlerini izleyin.",["lowWater","perennial"]),
    c("sorghum","Sorghum + cowpea rotation","Sorgum + börülce rotasyonu",[...A,...S,...R],field,180,.65,.94,.74,.66,"annual",15,65,45,"Use drought-tolerant local seed and keep residue management in the fire plan.","Kuraklığa dayanıklı yerel tohum kullanın; sap yönetimini yangın planına dahil edin.",["lowWater","resilient"]),
    c("millet","Millet + pulse rotation","Darı + bakliyat rotasyonu",[...A,...S,...R],field,105,.35,.96,.83,.56,"annual",10,40,30,"A short-season grain block; rotate and avoid leaving dry standing biomass.","Kısa sezonlu tahıl bloğu; rotasyon yapın ve kuru sapları ayakta bırakmayın.",["lowWater","resilient"]),
    c("cowpea","Cowpea + managed mulch","Börülce + kontrollü malç",[...A,...M,...S,...R],garden,145,.85,.92,.75,.61,"annual",20,60,35,"Use as food and seasonal soil cover; remove diseased residue after harvest.","Gıda ve mevsimlik toprak örtüsü olarak kullanın; hastalıklı artığı hasat sonrası kaldırın.",["food","resilient"]),
    c("pricklyPear","Prickly pear production block","Frenk inciri üretim bloğu",[...A,...M],warm,35,2.2,.99,.94,.68,"perennial",250,350,35,"Keep away from paths and fire access; use a managed harvest block, not a boundary hedge.","Patika ve yangın erişiminden uzak tutun; sınır çiti değil kontrollü hasat bloğu kurun.",["lowWater","resilient"]),
    c("moringa","Moringa + cowpea understory","Moringa + börülce alt katmanı",[...A,...S,...R],orchard,190,2.1,.86,.72,.76,"tree",300,400,55,"Protect from cold and prune as a managed small tree above seasonal legumes.","Soğuktan koruyun; mevsimlik baklagil üzerinde kontrollü küçük ağaç olarak budayın.",["food","resilient"]),

    c("plum","Plum + flowering understory","Erik + çiçekli alt katman",[...T,...C],orchard,330,2.7,.66,.58,.72,"tree",450,500,65,"Match rootstock, chill and pollination; keep airflow through the mature crown.","Anaç, soğuklama ve tozlanmayı eşleştirin; olgun taçta hava akışını koruyun.",["food","perennial"]),
    c("cherry","Cherry + low flowering strip","Kiraz + alçak çiçek şeridi",[...T,...C],orchard,350,2.5,.58,.5,.83,"tree",500,550,70,"Avoid frost pockets and waterlogged ground; verify compatible pollination.","Don çukuru ve su tutan zeminden kaçının; uyumlu tozlanmayı doğrulayın.",["food","income"]),
    c("hazelnut","Hazelnut coppice + shade herbs","Fındık ocağı + gölge otları",[...T,...C],orchard,310,1.4,.72,.68,.82,"shrub",350,450,55,"Maintain ventilated stools and harvest lanes; avoid crowding wet sites.","Havalanan ocaklar ve hasat koridorları bırakın; nemli alanı sıkıştırmayın.",["perennial","income"]),
    c("potato","Potato + legume rotation","Patates + baklagil rotasyonu",[...T,...C],garden,360,3.5,.63,.5,.67,"annual",30,75,35,"Rotate outside the nightshade family and keep the bed freely drained.","Patlıcangiller dışına rotasyon yapın ve yatağı iyi drene tutun.",["food","quick"]),
    c("pea","Pea trellis + summer follow crop","Bezelye askısı + yazlık ardıl ürün",[...T,...C,...M],small,190,1.4,.76,.62,.54,"annual",8,55,30,"Place trellis where it will not shade the following crop; rotate legumes.","Askıyı ardıl ürünü gölgelemeyecek yere koyun; baklagil rotasyonu yapın.",["food","quick"]),
    c("cabbage","Cabbage family rotation block","Lahana grubu rotasyon bloğu",[...T,...C],garden,390,4,.61,.42,.58,"annual",45,70,35,"Use a dedicated rotation block and monitor pest pressure before repeating brassicas.","Ayrı rotasyon bloğu kullanın; lahanagilleri tekrarlamadan zararlı baskısını izleyin.",["food","quick"]),
    c("raspberry","Raspberry rows + living aisle","Ahududu sırası + yaşayan koridor",[...T,...C],orchard,360,2.1,.62,.45,.8,"shrub",55,220,40,"Provide airflow, support and a contained root strip; avoid hot reflected walls.","Hava akışı, destek ve sınırlı kök şeridi sağlayın; sıcak yansıtan duvarlardan kaçının.",["food","income"]),

    c("sourCherry","Sour cherry + meadow strip","Vişne + çayır şeridi",[...C,...T],orchard,280,2.2,.78,.69,.7,"tree",450,500,65,"A colder-site fruit option; keep meadow growth low near trunks and access.","Soğuk alan meyvesi; gövde ve erişim yakınında çayır gelişimini kısa tutun.",["resilient","food"]),
    c("currant","Currant + woodland-edge herbs","Frenk üzümü + orman kenarı otları",[...C,...T],small,260,1.7,.8,.7,.68,"shrub",120,180,35,"Use in cool partial shade with airflow and an accessible picking edge.","Serin yarı gölgede, hava akışı ve erişilebilir hasat kenarıyla kullanın.",["food","perennial"]),
    c("gooseberry","Gooseberry + low herb edge","Bektaşi üzümü + alçak ot kenarı",[...C,...T],small,250,1.6,.77,.69,.66,"shrub",130,180,35,"Keep the canopy open and locate thorny plants away from narrow paths.","Tacını açık tutun; dikenli bitkiyi dar patikadan uzak yerleştirin.",["food","perennial"]),
    c("kale","Kale succession + winter mulch","Karalahana ardışık ekim + kış malçı",[...C,...T],small,260,3.1,.88,.7,.47,"annual",40,60,30,"Stagger planting and rotate the brassica family between beds.","Dikimi kademelendirin ve lahanagilleri yataklar arasında döndürün.",["food","resilient"]),
    c("rye","Rye cover and grain strip","Çavdar örtü ve tahıl şeridi",[...C,...T],field,90,.45,.96,.9,.43,"annual",4,20,25,"Use as a managed winter cover or grain strip; terminate before it competes with young trees.","Kontrollü kış örtüsü veya tahıl şeridi; genç ağaçlarla yarışmadan sonlandırın.",["lowWater","resilient"]),
    c("oat","Oat + clover rotation","Yulaf + üçgül rotasyonu",[...C,...T],field,125,.5,.9,.84,.45,"annual",5,22,25,"Rotate with a pulse and manage mature dry residue before fire season.","Bakliyatla rotasyon yapın; olgun kuru sapı yangın sezonundan önce yönetin.",["resilient","food"]),
    c("seaBuckthorn","Sea buckthorn shelter block","Yalancı iğde koruma bloğu",[...C,...T],orchard,80,.9,.98,.86,.68,"shrub",250,350,55,"Confirm sex ratio and contain suckering; do not place across critical access.","Dişi-erkek oranını doğrulayın ve dip sürgünlerini sınırlayın; kritik erişimi kapatmayın.",["lowWater","resilient"]),

    c("avocado","Avocado + shallow shade layer","Avokado + sığ gölge katmanı",S,orchard,720,3.2,.38,.38,.9,"tree",600,700,75,"Reserve excellent drainage, wind shelter and reliable water; avoid cold pockets.","Çok iyi drenaj, rüzgâr koruması ve güvenilir su ayırın; soğuk çukurlardan kaçının.",["food","income"]),
    c("guava","Guava + managed groundcover","Guava + kontrollü yer örtüsü",[...S,...R],orchard,380,3.4,.72,.68,.72,"tree",400,450,60,"Prune for harvest access and maintain an open, managed ground layer.","Hasat erişimi için budayın; açık ve kontrollü yer katmanı bırakın.",["food","perennial"]),
    c("passionfruit","Passionfruit trellis + herbs","Çarkıfelek askısı + otlar",[...S,...R],small,520,4.1,.52,.35,.82,"vine",250,300,45,"Use a strong trellis outside tree crowns and separate its irrigation zone.","Ağaç taçları dışında sağlam askı kullanın ve sulama bölgesini ayırın.",["food","income"]),
    c("turmeric","Turmeric under light canopy","Hafif taç altında zerdeçal",[...S,...R],small,480,2.8,.58,.62,.74,"perennial",30,55,30,"Use under light seasonal shade in rich, freely drained soil.","Zengin ve iyi drene toprakta hafif mevsimsel gölge altında kullanın.",["food","income"]),
    c("ginger","Ginger + humid shade bed","Zencefil + nemli gölge yatağı",[...S,...R],small,560,2.5,.45,.45,.8,"perennial",25,45,30,"Give afternoon shade, drainage and a separate moisture-managed bed.","Öğleden sonra gölgesi, drenaj ve nemi ayrı yönetilen yatak sağlayın.",["food","income"]),
    c("tea","Tea shrub contour rows","Çay çalısı kontur sıraları",S,orchard,650,.8,.57,.43,.78,"shrub",110,160,50,"Use only in humid acidic conditions; align rows after a real contour survey.","Yalnızca nemli asidik koşulda kullanın; sıraları gerçek kontur ölçümünden sonra hizalayın.",["income","perennial"]),
    c("banana","Banana circle + biomass edge","Muz çemberi + biyokütle kenarı",[...S,...R],orchard,920,5.8,.36,.4,.76,"perennial",250,350,55,"Use only with reliable water, wind shelter and a clear drainage route.","Yalnızca güvenilir su, rüzgâr koruması ve açık drenaj hattıyla kullanın.",["food","perennial"]),

    c("cassava","Cassava + pigeon-pea strip","Manyok + güvercin bezelyesi şeridi",R,garden,260,4.8,.91,.75,.6,"perennial",90,110,45,"Use locally suitable varieties and keep harvest beds out of erosion routes.","Yerel uygun çeşitleri kullanın; hasat yataklarını erozyon hatlarından uzak tutun.",["food","resilient"]),
    c("plantain","Plantain + legume ground layer","Plantain + baklagil yer katmanı",R,orchard,900,6,.48,.4,.74,"perennial",280,350,55,"Create a moist biomass zone with reliable water and wind protection.","Güvenilir su ve rüzgâr korumasıyla nemli biyokütle bölgesi kurun.",["food","perennial"]),
    c("pineapple","Pineapple contour blocks","Ananas kontur blokları",R,garden,310,3.5,.78,.7,.76,"perennial",35,65,30,"Use freely drained blocks and keep crowns accessible for inspection.","İyi drene bloklar kullanın; taçları kontrol için erişilebilir tutun.",["food","income"]),
    c("taro","Taro wet-zone bed","Taro nemli alan yatağı",R,garden,820,4.2,.35,.5,.63,"perennial",50,80,40,"Confine to a known wet zone; do not assume stagnant water is safe or suitable.","Bilinen nemli bölgeyle sınırlayın; durgun suyun güvenli veya uygun olduğunu varsaymayın.",["food","perennial"]),
    c("yam","Yam trellis + legume edge","Yam askısı + baklagil kenarı",R,garden,510,4.1,.68,.5,.67,"vine",90,140,55,"Provide a durable support and keep digging away from perennial roots.","Dayanıklı destek sağlayın; hasat kazısını çok yıllık köklerden uzak tutun.",["food","resilient"]),
    c("cacao","Cacao under managed shade","Kontrollü gölgede kakao",R,orchard,780,.9,.3,.28,.94,"tree",300,350,60,"A humid lowland specialist; build shade gradually and verify disease pressure locally.","Nemli alçak bölge uzmanı; gölgeyi kademeli kurun ve hastalık baskısını yerelde doğrulayın.",["income","perennial"]),
    c("coffee","Coffee under open canopy","Açık taç altında kahve",[...R,...S],orchard,590,1.1,.48,.36,.91,"shrub",180,260,45,"Match altitude and temperature, then maintain ventilated partial shade.","Rakım ve sıcaklığı eşleştirin; ardından havalanan yarı gölgeyi koruyun.",["income","perennial"]),
    c("coconut","Coconut + wide productive alley","Hindistan cevizi + geniş üretim koridoru",R,orchard,680,2.4,.67,.65,.72,"tree",800,900,100,"Reserve a very large crown and safe drop zone; keep buildings and paths clear.","Çok geniş taç ve güvenli düşme alanı ayırın; yapı ve patikaları uzak tutun.",["food","perennial"]),
    c("pigeonPea","Pigeon pea support strip","Güvercin bezelyesi destek şeridi",[...R,...S,...A],garden,130,1.2,.95,.8,.55,"shrub",80,140,45,"Use as a short-lived support shrub; prune before it shades annual crops.","Kısa ömürlü destek çalısı olarak kullanın; yıllıkları gölgelemeden budayın.",["lowWater","resilient"]),
    c("papaya","Papaya + low herb ring","Papaya + alçak ot halkası",[...R,...S],orchard,620,5.2,.42,.42,.75,"tree",250,320,45,"Use in frost-free, sheltered, freely drained ground with reliable water.","Don görmeyen, korunaklı, iyi drene ve güvenilir suyu olan zeminde kullanın.",["food","quick"]),

    c("broadBean","Broad bean + winter greens","Bakla + kışlık yapraklılar",[...M,...T],garden,180,1.5,.79,.67,.55,"annual",20,55,35,"Use as a cool-season food block and rotate away from legumes next season.","Serin dönem gıda bloğu olarak kullanın; sonraki sezon baklagil dışına rotasyon yapın.",["food","quick"]),
    c("garlic","Garlic + summer follow crop","Sarımsak + yazlık ardıl ürün",[...M,...T,...C],small,120,.8,.86,.78,.69,"annual",12,30,25,"Keep the bed freely drained and follow with a different plant family.","Yatağı iyi drene tutun; ardından farklı bir bitki familyasına geçin.",["lowWater","income"]),
    c("melon","Melon on managed mulch","Kontrollü malçta kavun",[...M,...A,...S],garden,310,3.4,.72,.48,.7,"annual",90,160,40,"Give vines a defined sunny block and keep fruit off wet soil.","Sürgünlere belirli güneşli bir blok verin; meyveyi ıslak topraktan uzak tutun.",["food","quick"]),
    c("durumWheat","Durum wheat + pulse rotation","Makarnalık buğday + bakliyat rotasyonu",[...M,...A,...T],field,110,.42,.85,.81,.6,"annual",4,20,30,"Use a locally timed grain block and manage dry residue before fire season.","Yerel takvime göre tahıl bloğu kurun; kuru sapı yangın sezonundan önce yönetin.",["lowWater","food"]),
    c("oregano","Oregano production strip","Keklik otu üretim şeridi",[...M,...A],small,75,.75,.96,.9,.74,"perennial",30,50,25,"Keep harvest strips open and avoid dense dry biomass beside buildings.","Hasat şeritlerini açık tutun; yapı yanında yoğun kuru biyokütle bırakmayın.",["lowWater","income"]),

    c("quinoa","Quinoa + pulse rotation","Kinoa + bakliyat rotasyonu",[...A,...T],field,125,.32,.9,.72,.67,"annual",15,45,35,"Match sowing time and variety to local heat, frost and day length.","Ekim zamanı ve çeşidi yerel sıcaklık, don ve gün uzunluğuna uydurun.",["lowWater","food"]),
    c("saffron","Saffron raised strip","Safran yükseltilmiş şeridi",[...A,...M,...T],small,80,.06,.88,.63,.92,"perennial",12,25,20,"Reserve a small, well-drained trial block before scaling this labour-heavy crop.","Emek yoğun ürünü büyütmeden önce küçük ve iyi drene bir deneme bloğu ayırın.",["lowWater","income"]),
    c("grainAmaranth","Grain amaranth + legume rotation","Tane amarant + baklagil rotasyonu",[...A,...S,...R],garden,150,.55,.89,.67,.62,"annual",25,60,35,"Use a warm-season block and prevent unwanted seed spread after harvest.","Sıcak dönem bloğu kullanın; hasat sonrası istenmeyen tohum yayılımını önleyin.",["resilient","food"]),
    c("dryWatermelon","Dryland watermelon trial","Kuru koşul karpuz denemesi",[...A,...M],garden,250,3.8,.78,.43,.68,"annual",100,180,45,"Start as a small local-variety trial; fruit load still depends on establishment water.","Yerel çeşitle küçük deneme yapın; meyve yükü yine kuruluş suyuna bağlıdır.",["food","resilient"]),

    c("beet","Beet succession beds","Pancar ardışık yatakları",[...T,...C,...M],small,240,2.8,.76,.7,.52,"annual",12,35,25,"Stagger sowing in cool periods and rotate away from the same family.","Serin dönemde ekimi kademelendirin; aynı familyadan sonra rotasyon yapın.",["food","quick"]),
    c("broccoli","Broccoli rotation block","Brokoli rotasyon bloğu",[...T,...C],garden,360,2.6,.65,.42,.66,"annual",45,70,35,"Keep a dedicated brassica rotation and monitor pests before replanting.","Ayrı lahanagil rotasyonu uygulayın; yeniden dikimden önce zararlıları izleyin.",["food","quick"]),
    c("blueberry","Blueberry acidic bed","Yaban mersini asitli yatağı",[...T,...C],small,410,1.6,.57,.46,.87,"shrub",120,180,35,"Use only after confirming acidic soil or a contained suitable growing medium.","Yalnızca asitli toprak ya da uygun sınırlı yetiştirme ortamı doğrulandıktan sonra kullanın.",["food","income"]),
    c("quince","Quince + flowering understory","Ayva + çiçekli alt katman",[...T,...M],orchard,300,2.7,.74,.67,.71,"tree",450,500,65,"Avoid waterlogged pockets and keep the mature crown accessible.","Su tutan çukurlardan kaçının; olgun tacı erişilebilir bırakın.",["food","perennial"]),
    c("chestnut","Chestnut + managed meadow","Kestane + kontrollü çayır",[...T,...C],orchard,330,1.2,.69,.73,.82,"tree",800,900,100,"Confirm acidic drainage, pollination and mature spacing before planting.","Dikimden önce asitli drenajı, tozlanmayı ve olgun aralığı doğrulayın.",["food","perennial"]),

    c("turnip","Turnip succession + cover","Şalgam ardışık ekim + örtü",[...C,...T],small,190,2.5,.87,.74,.45,"annual",15,35,25,"Use staggered cool-season sowings and rotate plant families.","Serin dönemde kademeli ekim yapın ve bitki familyalarını döndürün.",["food","quick"]),
    c("buckwheat","Buckwheat short-season strip","Karabuğday kısa sezon şeridi",[...C,...T],field,100,.35,.91,.86,.5,"annual",5,25,25,"Use as a short window crop and terminate before unwanted seed spread.","Kısa dönem ürünü olarak kullanın; istenmeyen tohum yayılımından önce sonlandırın.",["resilient","quick"]),
    c("aronia","Aronia + meadow aisle","Aronya + çayır koridoru",[...C,...T],orchard,240,1.3,.9,.8,.72,"shrub",160,250,40,"Maintain picking access and verify market demand before scaling.","Hasat erişimini koruyun; ölçek büyütmeden önce pazar talebini doğrulayın.",["resilient","perennial"]),
    c("haskap","Haskap paired rows","Mavi yemiş eşli sıraları",C,orchard,250,1.1,.92,.72,.78,"shrub",130,220,40,"Use compatible cultivars for pollination in reliably cold-winter sites.","Güvenilir soğuk kış alanlarında tozlanma için uyumlu çeşitleri birlikte kullanın.",["food","resilient"]),

    c("lychee","Lychee + managed ground layer","Liçi + kontrollü yer katmanı",S,orchard,560,2.4,.5,.45,.88,"tree",700,800,90,"Verify winter conditions, wind shelter and reliable establishment water.","Kış koşullarını, rüzgâr korumasını ve güvenilir kuruluş suyunu doğrulayın.",["food","income"]),
    c("macadamia","Macadamia + wide service alley","Makademya + geniş servis koridoru",S,orchard,500,1.7,.62,.56,.91,"tree",800,900,100,"Reserve mature crown space and verify cultivar, pollination and wind exposure.","Olgun taç alanı ayırın; çeşit, tozlanma ve rüzgâr maruziyetini doğrulayın.",["income","perennial"]),
    c("lemongrass","Lemongrass managed clumps","Limon otu kontrollü kümeleri",[...S,...R],small,360,2.2,.76,.78,.64,"perennial",70,100,35,"Keep clumps divided and away from narrow paths or dry fire edges.","Kümeleri bölerek yönetin; dar patika ve kuru yangın kenarlarından uzak tutun.",["food","perennial"]),
    c("sweetPepper","Sweet pepper + basil block","Tatlı biber + fesleğen bloğu",[...S,...M],small,480,5.4,.55,.43,.78,"annual",40,70,35,"Separate irrigation from drought herbs and rotate the nightshade family.","Sulamayı kurakçıl otlardan ayırın; patlıcangilleri rotasyona alın.",["food","income"]),

    c("breadfruit","Breadfruit + shade-tolerant understory","Ekmek ağacı + gölgeye dayanıklı alt katman",R,orchard,650,4.2,.62,.64,.72,"tree",900,1000,100,"Reserve a large safe crown area in humid frost-free conditions.","Nemli ve don görmeyen koşullarda geniş, güvenli taç alanı ayırın.",["food","perennial"]),
    c("jackfruit","Jackfruit + open harvest zone","Jackfruit + açık hasat bölgesi",R,orchard,620,4.8,.67,.56,.78,"tree",800,900,90,"Keep heavy fruit clear of paths and buildings; maintain harvest access.","Ağır meyveleri patika ve yapılardan uzak tutun; hasat erişimini koruyun.",["food","perennial"]),
    c("blackPepper","Black pepper on living support","Canlı destekte karabiber",R,orchard,700,1.1,.38,.3,.94,"vine",220,300,45,"Use only with humid shade, airflow and a disease-management plan.","Yalnızca nemli gölge, hava akışı ve hastalık yönetim planıyla kullanın.",["income","perennial"]),
    c("wingedBean","Winged bean on low trellis","Kanatlı fasulye alçak askısı",R,garden,360,2.1,.74,.5,.68,"vine",30,100,40,"Use a ventilated trellis in humid heat and rotate the legume family.","Nemli sıcakta havalanan askı kullanın; baklagil familyasını rotasyona alın.",["food","resilient"])
  ];
})();
